In [263]:
import pandas as pd

In [264]:
df = pd.read_excel(r"C:\Users\ASUS\Downloads\data_cleaning .xlsx", sheet_name="Usage",header = None, names = ['Raw'])
df

                                            Raw
0         3 PM  Mon 24th-Mar-2014___0.384 kwh
1                5AM  15-Aug-2014___1.201  kwh
2          __8PM Thu 20-Mar-2014____1.523 kwh
3               6PM  23rd-Apr-2014___0.424  kwh
4     _1AM  Friday 19th-Dec-2014___0.209  kwh
...                                         ...
8755         _1AM  Fri 07th-Nov-2014_0.084 kwh
8756                _6AM 20-May-2014__1.027 kwh
8757   __2 AM  Tuesday 8th-Apr-2014___0.052 kwh
8758            9 PM 27th-Jan-2014_1.428  kwh
8759          _12 PM 25th-Aug-2014_0.528  kwh

[8760 rows x 1 columns]

In [265]:
#deleting spaces and _ on both sides of string
df['Raw'] = df['Raw'].str.strip('_ ')

In [266]:
#splitting into two columns date and energy
df[['Datetime','Energy']] = df['Raw'].str.split(r'_+', n=1, expand = True)

In [267]:
#extracting usage kwh
df["Usage_Kwh"] = df['Energy'].str.extract(r'([\d\.]+)').astype(float)
df.drop(["Energy"], axis = 1, inplace = True)

In [268]:
#Extracting only hours in "XPM/XAM"
df["Hour"] = df['Datetime'].str.extract(r'(\d{1,2}\s*([a-zA-Z]{2}))')[0].str.replace(" ","")

In [269]:
df

,Raw,Datetime,Usage_Kwh,Hour
0,3 PM Mon 24th-Mar-2014___0.384 kwh,3 PM Mon 24th-Mar-2014,0.384,3PM
1,5AM 15-Aug-2014___1.201 kwh,5AM 15-Aug-2014,1.201,5AM
2,8PM Thu 20-Mar-2014____1.523 kwh,8PM Thu 20-Mar-2014,1.523,8PM
3,6PM 23rd-Apr-2014___0.424 kwh,6PM 23rd-Apr-2014,0.424,6PM
4,1AM Friday 19th-Dec-2014___0.209 kwh,1AM Friday 19th-Dec-2014,0.209,1AM
...,...,...,...,...
8755,1AM Fri 07th-Nov-2014_0.084 kwh,1AM Fri 07th-Nov-2014,0.084,1AM
8756,6AM 20-May-2014__1.027 kwh,6AM 20-May-2014,1.027,6AM
8757,2 AM Tuesday 8th-Apr-2014___0.052 kwh,2 AM Tuesday 8th-Apr-2014,0.052,2AM
8758,9 PM 27th-Jan-2014_1.428 kwh,9 PM 27th-Jan-2014,1.428,9PM
8759,12 PM 25th-Aug-2014_0.528 kwh,12 PM 25th-Aug-2014,0.528,12PM

In [ ]:
#Extracting date
df['Datetime'] = df['Datetime'].str.extract(r'(\d{1,2}[a-zA-Z]{0,2}-[a-zA-Z]{3}-\d{4})')

In [ ]:
#Deleting unnecessary date characters
df['Datetime'] = df['Datetime'].str.replace(r'(st|nd|rd|th)', '', regex=True)

In [ ]:
#Converting to datetime
df['Datetime'] = pd.to_datetime(df['Datetime'] + " " + df['Hour'], format='%d-%b-%Y %I%p')

In [ ]:
#Creating new date columns in order to better analyze
df['Month'] = df['Datetime'].dt.month_name()
df['Day_of_Week'] = df['Datetime'].dt.day_name()
df['Day'] = df['Datetime'].dt.day
df['Hour'] = df['Datetime'].dt.hour

In [164]:
df

,Raw,Datetime,Usage_Kwh,Hour,Month,Day_of_Week,Day
0,3 PM Mon 24th-Mar-2014___0.384 kwh,2014-03-24 15:00:00,0.384,15,March,Monday,24
1,5AM 15-Aug-2014___1.201 kwh,2014-08-15 05:00:00,1.201,5,August,Friday,15
2,8PM Thu 20-Mar-2014____1.523 kwh,2014-03-20 20:00:00,1.523,20,March,Thursday,20
3,6PM 23rd-Apr-2014___0.424 kwh,2014-04-23 18:00:00,0.424,18,April,Wednesday,23
4,1AM Friday 19th-Dec-2014___0.209 kwh,2014-12-19 01:00:00,0.209,1,December,Friday,19
...,...,...,...,...,...,...,...
8755,1AM Fri 07th-Nov-2014_0.084 kwh,2014-11-07 01:00:00,0.084,1,November,Friday,7
8756,6AM 20-May-2014__1.027 kwh,2014-05-20 06:00:00,1.027,6,May,Tuesday,20
8757,2 AM Tuesday 8th-Apr-2014___0.052 kwh,2014-04-08 02:00:00,0.052,2,April,Tuesday,8
8758,9 PM 27th-Jan-2014_1.428 kwh,2014-01-27 21:00:00,1.428,21,January,Monday,27
8759,12 PM 25th-Aug-2014_0.528 kwh,2014-08-25 12:00:00,0.528,12,August,Monday,25

In [ ]:
#Dropping unnecessary column
df.drop('Raw', axis = 1, inplace = True)

In [ ]:
#Sorting by datetime
df = df.sort_values('Datetime').reset_index(drop = True)

In [ ]:
#The data is ready for analysis and answering questions
df

                Datetime  Usage_Kwh  Hour     Month Day_of_Week  Day
0    2014-01-01 00:00:00      0.684     0   January   Wednesday    1
1    2014-01-01 01:00:00      0.340     1   January   Wednesday    1
2    2014-01-01 02:00:00      0.332     2   January   Wednesday    1
3    2014-01-01 03:00:00      0.396     3   January   Wednesday    1
4    2014-01-01 04:00:00      0.388     4   January   Wednesday    1
...                  ...        ...   ...       ...         ...  ...
8755 2014-12-31 19:00:00      1.940    19  December   Wednesday   31
8756 2014-12-31 20:00:00      1.901    20  December   Wednesday   31
8757 2014-12-31 21:00:00      0.766    21  December   Wednesday   31
8758 2014-12-31 22:00:00      0.633    22  December   Wednesday   31
8759 2014-12-31 23:00:00      0.600    23  December   Wednesday   31

[8760 rows x 6 columns]

In [ ]:
#Q1
#What is your average hourly electricity usage?
print(df['Usage_Kwh'].mean().round(3),"kwh") # The answer is B

0.782 kwh

In [ ]:
#Q2
#What is your average electricity usage perhour in February?
df[df['Month'] == 'February']['Usage_Kwh'].mean().round(3) # The answer is D

0.834

In [ ]:
#Q3
#Which day of the week has the highest average usage
df.groupby('Day_of_Week')['Usage_Kwh'].mean().idxmax() # The answer is A

'Sunday'

In [ ]:
#Q4
#What is the highest amount of electricity used in a continuous 4 hour period?
df['Usage_Kwh'].rolling(window=4).sum().max() # The answer is A

17.237000000000002

In [213]:
#Question 5 Based on your historic electricity usage, what would your annual cost of electricity be under the "Monthly Flex"?
df_contracts = pd.read_excel(r'c:\Users\ASUS\Downloads\data_cleaning .xlsx', sheet_name="Contracts")

In [ ]:
#Creating a dataframe for monthly flex
monthly_flex = df_contracts.iloc[11:23,4:6]
monthly_flex.columns =["Month","Rate"]
monthly_flex["Rate"] = monthly_flex["Rate"].astype(float)
monthly_flex

        Month  Rate
11    January  0.20
12   February  0.19
13      March  0.17
14      April  0.18
15        May  0.22
16       June  0.27
17       July  0.24
18     August  0.19
19  September  0.18
20    October  0.15
21   November  0.14
22   December  0.19

In [ ]:
#Creating a dataframe for usage by month and merging with monthly flex
usage_by_month = df.groupby('Month')['Usage_Kwh'].sum()
merged_data = pd.merge(usage_by_month, monthly_flex, on='Month')
merged_data

        Month  Usage_Kwh  Rate
0       April    151.666  0.18
1      August    635.819  0.19
2    December    568.948  0.19
3    February    559.436  0.19
4     January   1042.660  0.20
5        July   1255.351  0.24
6        June    899.904  0.27
7       March    422.655  0.17
8         May    416.813  0.22
9    November    232.420  0.14
10    October    313.719  0.15
11  September    348.723  0.18

In [ ]:
#Calculating annual cost
merged_data['Cost'] = merged_data["Usage_Kwh"] * merged_data["Rate"]
monthly_cost = merged_data['Cost'].sum() 
print(monthly_cost) # The answer is B

1421.20577

In [259]:
#Question 6 Based on your historic electricity usage, which of the three contracts would pro-duce the lowest annual cost?
# Monthly contract will be 1421.20577

#Flat rate
flat_rate_cost = df.groupby('Month')['Usage_Kwh'].sum().sum() * 0.21
print(flat_rate_cost)
#1438.10394 will be flat rate annual cost

1438.10394

In [ ]:
#Hourly contract
hourly_flex = df_contracts.iloc[11:35,8:10].reset_index(drop = True)
hourly_flex.columns = ["Hour","Rate"]

In [ ]:
#Creating a dataframe for hourly flex
hourly_flex['Hour'] = range(24) #This transforms our long string format hours to integer in order to merge with our main dataframe
hourly_flex['Hour'] = hourly_flex['Hour'].astype(int)
hourly_flex

    Hour  Rate
0      0  0.10
1      1  0.10
2      2  0.10
3      3  0.10
4      4  0.15
5      5  0.20
6      6  0.24
7      7  0.24
8      8  0.26
9      9  0.20
10    10  0.20
11    11  0.26
12    12  0.26
13    13  0.20
14    14  0.24
15    15  0.18
16    16  0.15
17    17  0.30
18    18  0.24
19    19  0.24
20    20  0.12
21    21  0.11
22    22  0.10
23    23  0.10

In [ ]:
#Merging useful columns
hourly_cost = pd.merge(df[['Hour','Month',"Usage_Kwh"]], hourly_flex, on = 'Hour')

In [ ]:
#Calculating annual cost for hourly flex
hourly_cost['Cost'] = hourly_cost['Usage_Kwh'] * hourly_cost['Rate']
hourly_cost = hourly_cost['Cost'].sum()

#Comparison of contracts
print(hourly_cost) # The hourly cost has lowest annual cost relative to others then answer is C
print(monthly_cost)
print(flat_rate_cost)

1368.97647
1421.20577
1438.10394